package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Default Sage/Olive colors (SAGE)
val LightSagePrimary = Color(0xFF5D624E)
val LightSageOnPrimary = Color(0xFFFFFFFF)
val LightSagePrimaryContainer = Color(0xFFE6E3D3)
val LightSageSecondary = Color(0xFF5D624E)
val LightSageSecondaryContainer = Color(0xFFF3F1E9)
val LightSageBackground = Color(0xFFFBF9F1)
val LightSageSurface = Color(0xFFFFFFFF)

val DarkSagePrimary = Color(0xFFC4CBB1)
val DarkSageOnPrimary = Color(0xFF2F3325)
val DarkSagePrimaryContainer = Color(0xFF454A39)
val DarkSageSecondary = Color(0xFFD3D6C9)
val DarkSageSecondaryContainer = Color(0xFF404437)
val DarkSageBackground = Color(0xFF1C1C17)
val DarkSageSurface = Color(0xFF242620)

// Elegant Royal Blue (BLUE)
val LightBluePrimary = Color(0xFF1E40AF)
val LightBlueOnPrimary = Color(0xFFFFFFFF)
val LightBluePrimaryContainer = Color(0xFFDBEAFE)
val LightBlueSecondary = Color(0xFF3B82F6)
val LightBlueSecondaryContainer = Color(0xFFEFF6FF)
val LightBlueBackground = Color(0xFFF8FAFC)
val LightBlueSurface = Color(0xFFFFFFFF)

val DarkBluePrimary = Color(0xFF93C5FD)
val DarkBlueOnPrimary = Color(0xFF1E3A8A)
val DarkBluePrimaryContainer = Color(0xFF1E3A8A)
val DarkBlueSecondary = Color(0xFF60A5FA)
val DarkBlueSecondaryContainer = Color(0xFF1E293B)
val DarkBlueBackground = Color(0xFF0F172A)
val DarkBlueSurface = Color(0xFF1E293B)

// Vibrant Retail Crimson (CRIMSON)
val LightCrimsonPrimary = Color(0xFF9D174D)
val LightCrimsonOnPrimary = Color(0xFFFFFFFF)
val LightCrimsonPrimaryContainer = Color(0xFFFCE7F3)
val LightCrimsonSecondary = Color(0xFFDB2777)
val LightCrimsonSecondaryContainer = Color(0xFFFDF2F8)
val LightCrimsonBackground = Color(0xFFFFFDFD)
val LightCrimsonSurface = Color(0xFFFFFFFF)

val DarkCrimsonPrimary = Color(0xFFF472B6)
val DarkCrimsonOnPrimary = Color(0xFF831843)
val DarkCrimsonPrimaryContainer = Color(0xFF831843)
val DarkCrimsonSecondary = Color(0xFFF472B6)
val DarkCrimsonSecondaryContainer = Color(0xFF500724)
val DarkCrimsonBackground = Color(0xFF1C0D12)
val DarkCrimsonSurface = Color(0xFF27131A)

// Cozy Teal & Mint (TEAL)
val LightTealPrimary = Color(0xFF0F766E)
val LightTealOnPrimary = Color(0xFFFFFFFF)
val LightTealPrimaryContainer = Color(0xFFCCFBF1)
val LightTealSecondary = Color(0xFF14B8A6)
val LightTealSecondaryContainer = Color(0xFFF0FDFA)
val LightTealBackground = Color(0xFFF5FAF9)
val LightTealSurface = Color(0xFFFFFFFF)

val DarkTealPrimary = Color(0xFF2DD4BF)
val DarkTealOnPrimary = Color(0xFF115E59)
val DarkTealPrimaryContainer = Color(0xFF115E59)
val DarkTealSecondary = Color(0xFF5EEAD4)
val DarkTealSecondaryContainer = Color(0xFF134E4A)
val DarkTealBackground = Color(0xFF0B1414)
val DarkTealSurface = Color(0xFF111F1F)

// Golden Marigold & Amber (GOLDEN)
val LightGoldenPrimary = Color(0xFFB45309)
val LightGoldenOnPrimary = Color(0xFFFFFFFF)
val LightGoldenPrimaryContainer = Color(0xFFFEF3C7)
val LightGoldenSecondary = Color(0xFFF59E0B)
val LightGoldenSecondaryContainer = Color(0xFFFFFBEB)
val LightGoldenBackground = Color(0xFFFFFDF5)
val LightGoldenSurface = Color(0xFFFFFFFF)

val DarkGoldenPrimary = Color(0xFFFBBF24)
val DarkGoldenOnPrimary = Color(0xFF78350F)
val DarkGoldenPrimaryContainer = Color(0xFF78350F)
val DarkGoldenSecondary = Color(0xFFF59E0B)
val DarkGoldenSecondaryContainer = Color(0xFF451A03)
val DarkGoldenBackground = Color(0xFF14110B)
val DarkGoldenSurface = Color(0xFF1F1B11)

// Common helpers
val ProfitGreen = Color(0xFF2E7D32)
val LossRed = Color(0xFFC62828)
val LightProfitBg = Color(0xFFE8F5E9)
val LightLossBg = Color(0xFFFFEBEE)
val GoldColor = Color(0xFFF59E0B)
